### ISSUE TITLE
Error connecting to private installation through UltraSonic

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/navidrome_ynh#10]
**Describe the bug**
Attempting to connect to a private Navidrome YunoHost installation via UltraSonic yields an error:

> Connection failure. Didn't understand the reply. Please check the server address.

**System details**
- UltraSonic: 2.9.0 (Android)
- Navidrome: 0.30.1~ynh
- YunoHost: 4.0.4
- Navidrome installation: private (YunoHost login required in addition to Navidrome login)

**To Reproduce**
1. Install Navidrome on YunoHost. Mark it as a private installation.
2. Create a user for Navidrome.
3. Install UltraSonic for Android.
4. In UltraSonic, add the Navidrome server:
  - Server Address: path to Navidrome (example.com/navidrome)
  - Username: user created above
  - Password: user created above
  - Enabled: checked
  - Allow self-signed HTTPS certificate: checked
5. In UltraSonic, tap "Test Server".

**Expected Behavior**
UltraSonic logs into the server.

**Notes**
- I suspect this is because a private Navidrome installation has two login screens to get through: first the YunoHost sign-in, then the Navidrome one. If UltraSonic is expecting a single sign-in screen that leads directly to the Navidrome installation, it won't get a response that matches that.
- It doesn't seem to matter if I check the "Enable support for LDAP users" in UltraSonic.
- I've tried entering credentials for both my Navidrome user and my YunoHost user. Neither has fixed this issue.
- I've also tried entering my wife's credentials, which are the same for Navidrome and YunoHost. That didn't fix it either.
- I'm raising this issue here because it seems in part related to the YunoHost packaging, but I also recognize it might require an upstream change and/or a change to UltraSonic. Please pardon me if this is totally outside of this repo's scope.

**Comment by ericgaspar** [comment]
What happens if you switch Navidrome to public? (Admin console -> Users -> Manage groups and authorizations -> Visitors -> Add a permission -> Navidrome)

**Comment by SpencerDub** [comment]
That does it! And since Navidrome requires a login, I guess it's not like I'm actually opening the server to random internet strangers.

@ericgaspar, thanks for your help with all this. I hope I haven't been too much of a pest; I really appreciate you pulling this package together.

**Comment by praise-you** [comment]
> Server Address: path to Navidrome (example.com/navidrome)

Newcomers beware, don't loose as much time as I did with your connection problem. You probably have to modify the path to your server like I had to. Instead of "https://user.yunohost.tld" use "https://user.yunohost.tld/navidrome"!

Thanks @SpencerDub for pointing this out. I felt dumb and I learned a thing.

Cheers
