### ISSUE TITLE
Where is ui/src/themes?

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/navidrome_ynh#11]
With any luck, this will be the last issue I open for a while. 

The [Navidrome documentation](https://www.navidrome.org/docs/developers/creating-themes/) says that you can create a new theme at `ui/src/themes`, but I can't find that directory on my YunoHost server. I've checked `/var/lib/navidrome` and `/opt/yunohost/navidrome`, and neither has a `ui` folder.

Where would I find this folder? Alternatively, if it needs to be created, where would I put it?

Thanks!

**Comment by ericgaspar** [comment]
It's a path in the source files of the upstream git repo: https://github.com/deluan/navidrome/tree/master/ui/src/themes, so, if you want to add a theme, you may need to build Navidrome from source. The YunoHost package uses the precompiled binaries.

**Comment by SpencerDub** [comment]
Ahh, okay. That would explain it. Thanks!
