### ISSUE TITLE
Installing Navidrome under a custom path causes it to not load when clicked

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/navidrome_ynh#2]
**Describe the bug**
If the package was installed under a **non-default path** (that is, *not* `/navidrome`), then clicking the Navidrome link in the YunoHost control panel or directly entering the Navidrome installation's URL does not load the Navidrome app. Instead, it just loads the YunoHost control panel.

**Versions**
- Hardware: Old laptop or computer
- YunoHost version: 4.0.4
- I have access to my server: Through SSH (and via direct access if needed)
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: yes
  - If yes, please explain: behind a Raspberry Pi reverse proxy
- Using, or trying to install package version/branch: `master`

**To Reproduce**
1. Log in to the YunoHost admin panel. Click "Applications" -> "Install". Search for Navidrome in the catalog and fail to find it.
2. In the "Install custom app" part of the window, paste `https://github.com/YunoHost-Apps/navidrome_ynh` and click "Install". Confirm the warning.
3. Fill out installation preferences. I chose a domain (the same as the domain that YunoHost is on), set `/tunez` as the installation path, and deselected the "public site" option.
4. Once YunoHost finishes installing, navigate to `mydomain.com/tunez`. Alternatively, log into YunoHost and click the Navidrome tile.

**Expected behavior**
The Navidrome login page loads, presumably to the create-an-admin login screen (as experienced when the app is installed under `/navidrome`).

**Encountered behavior**
The YunoHost control panel is returned instead.

**Additional info:**
* Attempting to change the installed Navidrome app's path via YunoHost does not work; once installed at a custom path, it appears to stay there.
* If I uninstall Navidrome and install it again, exactly the same as steps 1-4 above, but I do *not* pick a custom path, Navidrome installs properly at `mydomain.com/navidrome`, and clicking the tile or navigating to that URL properly directs to `mydomain.com/navidrome/app/#/login`.

**Comment by ericgaspar** [comment]
Thank you for reporting this issue! It should now be fixed, can you try it?

**Comment by SpencerDub** [comment]
Yes, this resolves it! Thank you.
