### ISSUE TITLE
yunohost.navidrome music folder issues

### ISSUE THREAD

**Issue by praise-you** [YunoHost-Apps/navidrome_ynh#24]
Hey, thanks a lot for navidrome on yunohost!
First thing first: I've done a clean install of debian and then installed the yunohost package.

I run into a problem: /home/yunohost.navidrome makes sense as a default folder but I'm totally unable to upload there. I've tried the official "admin" and the user I've created to host navidrome and always get permission denied.

I'm not good at Linux so it may be on my side, but as I run a new instance...

**Comment by ericgaspar** [comment]
Hi  @praise-you 
-  If you want to use an FTP client to upload your music to the `/home/yunohost.navidrome/Music` folder you can add your UserName (the YunoHost UserName) to the www-data group:
` sudo usermod -a -G www-data UserName` then connect to an FTP clent using your YunoHost username and password.
- If you already have an existing Media folder with right access, you can also point to this folder by changing the Navidrome settings: `/var/lib/navidrome/navidrome.toml` -> MusicFolder
Tell me if it works for you

**Comment by ericgaspar** [comment]
Good to hear!
`/home/yunohost.multimedia/user/Music` seems like a good place to store media as it's also accessible with Nextcloud with *External storage support* on.
I still need to fine-tune the default settings for storage, default setting and authorization issues.
Feel free to do a PR if you think of something that will improve the user experience. (I will put CovertArtPriority to setting as default #25)

**Comment by praise-you** [comment]
Great! Thank you

**Comment by TiberiusRegenschein** [comment]
I like the suggestion to follow the multimedia folder structure established. In my case I even used the unohost.multimedia share folder. Maybe allow for setting the variable initially during installation. I was fine changing it in the .toml file.

App works very well on my X86 server 👍

**Comment by jmbmkn** [comment]
I've pointed the .toml file to my music collection at /home/yunohost.multimedia/share/Music but the music is not appearing in Navidrome. Am I missing a step?

**Comment by praise-you** [comment]
Hey @ericgaspar I've updated to 0.34 and everything runs smooth. Many thanks to you!! I suppose this issue can now be closed?

**Comment by ericgaspar** [comment]
Change default media folder in #28

**Comment by TheNomad11** [comment]
> I've pointed the .toml file to my music collection at /home/yunohost.multimedia/share/Music but the music is not appearing in Navidrome. Am I missing a step?
> 
> Edit:I restarted the service from inside the ynh web admin interface and that fixed it

Can this be added to the documentation? Without restarting the service no new music showed up
