### ISSUE TITLE
Suggestion: make CovertArtPriority default 

### ISSUE THREAD

**Issue by praise-you** [YunoHost-Apps/navidrome_ynh#25]
Hi,
To make Navidrome even more userfriendly on YNH I suggest this parameter is added to each new install:
CovertArtPriority = "embedded, cover.*, folder.*, front.*"
This has been taken from the official wiki, maybe there's a better filter?
Thanks,

**Comment by ericgaspar** [comment]
CovertArtPriority  added on #28
