### ISSUE TITLE
Web UI: Move Yunohost logo a few pixels higher

### ISSUE THREAD

**Issue by praise-you** [YunoHost-Apps/navidrome_ynh#26]
Hello,

Yunohost's logo get in the way of the web player:
![yn](https://user-images.githubusercontent.com/67846246/93669654-fa9ebe80-fa95-11ea-8635-bd8136733920.png)
It would be nice to move it a few pixels higher (or just hide it).

The solution I found is to block the logo with a browser plugin. Maybe there's a nicer way to do it?
Thanks

**Comment by ericgaspar** [comment]
Hello @praise-you 
Two solutions:
1. The YunoHost logo is movable (you can also drag it out of the window)
2. You can edit the CSS file `/usr/share/ssowat/portal/assets/css/ynh_overlay.css`
ligne 41 set to: `dislplay: none;`
This will be overwritten in the next update

**Comment by praise-you** [comment]
> The YunoHost logo is movable (you can also drag it out of the window)

What? It is? I feel stupid...

Thanks for the CSS tip.

Cheers!
