### ISSUE TITLE
Version on Yunohost is still 0.35.0

### ISSUE THREAD

**Issue by praise-you** [YunoHost-Apps/navidrome_ynh#32]
Hi Eric,
Many thanks to you to keep Navidrome updated!!
For some reason the latest version on Yunohost is 0.35.0 whereas you've seem to have updated this repo to 0.35.1.
I've run the update mechanism twice and there's no update.
Did I do something wrong?

**Comment by ericgaspar** [comment]
@praise-you  mmh, no idea why you don't get the package updated... 0.35.1 is a minor release. You shoudn't miss any new features, let's wait for the next update to see how it goes.

**Comment by praise-you** [comment]
Thanks a lot for upgrading Navidrome to 0.36 in such a timely fashion! My server bumped Navidrome to the latest version.

**Comment by praise-you** [comment]
And it bumped to 0.36.1 too. Thanks, I'm closing this.
