### ISSUE TITLE
Docker Container doesn't work "No admin user found!"

### ISSUE THREAD

**Issue by TaakoMagnusen** [YunoHost-Apps/navidrome_ynh#46]
These are my docker  settings [1](https://i.imgur.com/kdxwFuG.png) [2](https://i.imgur.com/6ycYcEd.png)

The page is stuck on "Loading. The page is loading, just a moment please."

Got this error:

    
    | \ | | (_) | |
    | \| | __ ___ ___ __| |_ __ ___ _ __ ___ ___
    | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
    | |\ | (_| |\ V /| | (_| | | | (_) | | | | | | __/
    \_| \_/\__,_| \_/ |_|\__,_|_| \___/|_| |_| |_|\___|
    Version: 0.41.0 (ba922bbf)
    
    
    2021/04/04 04:01:38 goose: no migrations to run. current version: 20210322132848
    
    time="2021-04-04T04:01:38Z" level=info msg="Starting scanner" interval=1m0s
    time="2021-04-04T04:01:38Z" level=info msg="Configuring Media Folder" name="Music Library" path=/music
    time="2021-04-04T04:01:38Z" level=info msg="Creating Image cache" maxSize="200 MB" path=/data/cache/images
    time="2021-04-04T04:01:38Z" level=info msg="Finished initializing cache" cache=Image elapsedTime="239.018µs" maxSize=200MB
    time="2021-04-04T04:01:38Z" level=info msg="Found ffmpeg" path=/usr/bin/ffmpeg
    time="2021-04-04T04:01:38Z" level=info msg="Last.FM integration not available: missing ApiKey/Secret"
    time="2021-04-04T04:01:38Z" level=info msg="Spotify integration is not enabled: artist images will not be available"
    time="2021-04-04T04:01:38Z" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/data/cache/transcoding
    time="2021-04-04T04:01:38Z" level=info msg="Finished initializing cache" cache=Transcoding elapsedTime="176.034µs" maxSize=100MB
    time="2021-04-04T04:01:38Z" level=info msg="Mounting routes" path=/rest
    time="2021-04-04T04:01:38Z" level=info msg="Mounting routes" path=/app
    time="2021-04-04T04:01:38Z" level=info msg="Login rate limit set" requestLimit=5 windowLength=20s
    time="2021-04-04T04:01:38Z" level=info msg="Navidrome server is accepting requests" address="0.0.0.0:4533"
    time="2021-04-04T04:01:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:02:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:03:40Z" level=warning msg="No admin user found!" error="data not found"
    
    time="2021-04-04T04:03:40Z" level=warning msg="No admin user found!" error="data not found"

**Comment by ericgaspar** [comment]
This script doesn't need Docker to install Navidrome...

**Comment by TaakoMagnusen** [comment]
@ericgaspar what do you mean? What script?

**Comment by ericgaspar** [comment]
Just to be sure. You want to install Navidrome on Yunohost using navidrome_ynh?

**Comment by TaakoMagnusen** [comment]
oh shoot sorry i meant to post this on the general navidrome repo. my bad!
