### ISSUE TITLE
Where are logs stored?

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/navidrome_ynh#5]
Most of the YunoHost apps I've installed write logs to `/var/log`. I don't see a `/var/log/navidrome.log`. Are logs written elsewhere, or not being written at all?

I ask because I have another issue I want to troubleshoot--my library isn't scanning, but I'll create a new issue for that--but I can't figure out where the logs are to figure out what's going on.

Thanks!

**Comment by ericgaspar** [comment]
Thanks for beta testing the app :)

* Logs are in **YunoHost Admin  -> services -> navidrome**. I will add them to `var/log/navidrome.log`

* Path to the media library is to be found here `/var/lib/navidrome/navidrome.toml`
* The media path in line 7 should read `MusicFolder = "/home/yunohost.navidrome/Music"`

If you have a custom folder with you music you can change this path:
https://github.com/YunoHost-Apps/navidrome_ynh/blob/3a90243be3134eb5c7f671ceced1861601092f17/conf/navidrome.toml#L7

**Comment by SpencerDub** [comment]
@ericgaspar Great,thanks! I'll check them out in the Admin panel.

I'd changed the path before opening this issue, but something's still not working. Like I said, I'll open an issue about it when I have the chance, so as to keep issues separate.

Thanks for packaging the app! I sincerely appreciate it.
