### ISSUE TITLE
Revenir version antérieure (<0.43.0~ynh1)

### ISSUE THREAD

**Issue by CyrilleBiot** [YunoHost-Apps/navidrome_ynh#55]
Matériel: Olimex A20 Lime 2
Version de YunoHost: YunoHost 4.2.5.2 (stable)
J’ai accès à mon serveur : En SSH | Par la webadmin |
Êtes-vous dans un contexte particulier ou avez-vous effectué des modificiations particulières sur votre instance ? : non
Si oui, expliquer:
NAVIDROME : 0.43.0~ynh1
Description du problème

J’ai mis à jour l’ensemble du système et des applications hier.
Idiot que je suis j’ai également viré mes backup…

En lançant navidrome ce soir, je remarque :

    - que les vignettes des albums (80%) ne sont plus prises en charge
    - le lecteur ne démarre plus

J’aimerais revenir à la version antérieure par conséquent

Y aurait il une ligne de commande magique pour downgrader cette application uniquement ?

D’avance merci

**Comment by ericgaspar** [comment]
Closing with #57
