### ISSUE TITLE
No LDAP/SSO support

### ISSUE THREAD

**Issue by UserThre3** [YunoHost-Apps/navidrome_ynh#76]
### Describe the bug

No LDAP/SSO support.

### Steps to reproduce

Click on Navidrome on Yunohost panel leads to login screen, users have to be manually added through Navidrome admin interface. 

### Expected behavior

Users are automatically created from LDAP, log directly in to users profile when opening Navidrome.

**Comment by ericgaspar** [comment]
We need upstream to implement LDAP support to be able to provid it. see https://github.com/navidrome/navidrome/issues/141
