### ISSUE TITLE
[Bug] Manually changed navidrome.toml values resets after every update

### ISSUE THREAD

**Issue by krisu5** [YunoHost-Apps/navidrome_ynh#79]
~~I'm using different music folder location because of Syncthing. Everytime that Navidrome update happens, I have to reupload my `navidrome.toml` config because of the different folder location.~~

---

I double-checked this by restoring to 0.47.5\~ynh2 and updating to 0.47.5~ynh3

It did change `navidrome.toml` values back to default based of logs (see lines after `2022-07-06 13:22:31,744`): https://paste.yunohost.org/raw/qidijolabi

I also checked the file too and it was reseted.

I changed the title related to bug report, because I guess that should have been more appropriate. Sorry about that!

**Comment by ericgaspar** [comment]
`navidrome.toml` configuration file is regenerated when changes have been added (last time was to introduce settings made available in the control panel if I remember correctly).

**Comment by krisu5** [comment]
I double-checked this by restoring to 0.47.5~ynh2 and updating to 0.47.5~ynh3

It did change `navidrome.toml` values back to default based of logs (see lines after `2022-07-06 13:22:31,744`): https://paste.yunohost.org/raw/qidijolabi

I changed the title related to bug report, because I guess that should have been more appropriate. Sorry about that!

**Comment by ericgaspar** [comment]
It's not easy to manage. Users sometime skip versions and update the app with a version preserving their configuration file but with missing variables (breaking the configuration panel as a result).
