### ISSUE TITLE
Latest update doesn't install 

### ISSUE THREAD

**Issue by Chevrah** [YunoHost-Apps/navidrome_ynh#92]
See my logs. 

https://paste.yunohost.org/raw/upifasofeb

**Comment by ericgaspar** [comment]
Is upgrading with testing working? : `sudo yunohost app upgrade navidrome -u https://github.com/YunoHost-Apps/navidrome_ynh/tree/testing`

**Comment by ericgaspar** [comment]
fixed with #93
