### ISSUE TITLE
Service fails after upgrade to 0.49.2

### ISSUE THREAD

**Issue by zecamigo** [YunoHost-Apps/navidrome_ynh#94]
### Describe the bug

Service fails after upgrade from 0.48.0 to 0.49.2
(btw 0.48.0 to 0.49.0 was working fine asides the lost playlists)

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.1.6.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable

### Steps to reproduce
Upgrade from the webadmin

Note: the library location is customized (music files in an external disk)

### Logs

http request fails with 502 Bad Gateway

Feb 12 14:09:54 navidrome[3287782]:                           Version: 0.49.2 (3cd934ab)
Feb 12 14:09:54 navidrome[3287782]: time="2023-02-12T14:09:54Z" level=fatal msg="Failed to apply new migrations" error="ERROR 20230209181414_change_image_files_list_separator.go: failed to run Go migration function func(*sql.Tx) error: sql: Scan error on column index 1, name \"image_files\": converting NULL to string is unsupported"
Feb 12 14:09:54 systemd[1]: navidrome.service: Main process exited, code=exited, status=1/FAILURE
Feb 12 14:09:54 systemd[1]: navidrome.service: Failed with result 'exit-code'.
Feb 12 14:09:54 systemd[1]: navidrome.service: Scheduled restart job, restart counter is at 5.
Feb 12 14:09:54 systemd[1]: Stopped Navidrome Music Server and Streamer compatible with Subsonic/Airsonic.
Feb 12 14:09:54 systemd[1]: navidrome.service: Start request repeated too quickly.
Feb 12 14:09:54 systemd[1]: navidrome.service: Failed with result 'exit-code'.
Feb 12 14:09:54 systemd[1]: Failed to start Navidrome Music Server and Streamer compatible with Subsonic/Airsonic.

**Comment by ericgaspar** [comment]
Maybe an upstream bug... https://github.com/navidrome/navidrome/issues/2168

**Comment by zecamigo** [comment]
Yep, sorry I hadn't check. Closing this one.
