### ISSUE TITLE
Upgrade to 0.49.3

### ISSUE THREAD

**Issue by cnovel** [YunoHost-Apps/navidrome_ynh#95]
### Describe the bug
Migration from version <0.49.0 is broken with v0.49.2 ([see here](https://github.com/navidrome/navidrome/releases/tag/v0.49.3))

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.1.6.2 (stable).
- I have access to my server: *Through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: using v0.49.2

### Steps to reproduce
Install Navidrome with a version inferior to 0.49.0. Upgrade to 0.49.2, service is broken.

> 502 Bad Gateway
> 
> If you see this page, your connection with the server is working but the internal service providing this path is not responding.
> 
> Administrator, make sure that the service is running, and check its logs if it is not. The Services page is in your webadmin, under Tools > Services.
> 
> Thank you for using YunoHost.

[See logs](https://paste.yunohost.org/yugaziwara)

Updating the package to v0.49.3 should fix the issue.

### Expected behavior

/

### Logs
/

**Comment by ericgaspar** [comment]
same as this one? https://github.com/YunoHost-Apps/navidrome_ynh/issues/94

**Comment by ericgaspar** [comment]
should have been fixed with the last version...

**Comment by cnovel** [comment]
Yes sorry I missed that.

**Comment by cnovel** [comment]
Package has been updated, thanks!
